version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore
      - run:
          name: Run Tests
          command: cd ./NeatScrape.Tests && dotnet xunit -xml ~/tests/junit/xunit-test-results.xml
      - run:
          name: Setup Environment Variables
          command: echo 'export PATH="/root/.dotnet/tools:$PATH"' >> $BASH_ENV
      - run:
          name: Convert Test Results
          command: dotnet tool install --global dotnet-xunit-to-junit && dotnet xunit-to-junit ~/tests/junit/xunit-test-results.xml ~/tests/junit/test-results.xml
      - store_test_results:
          path: ~/tests
      - store_artifacts:
          path: ~/tests
          destination: test-results
      - persist_to_workspace:
          root: ~/project
          paths: .
  publish:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Pack
          command: dotnet pack ./NeatScrape/NeatScrape.csproj --output .
      - run:
          name: Publish
          command: dotnet nuget push ./NeatScrape/*.nupkg -k $NUGET_APIKEY -s https://api.nuget.org/v3/index.json
workflows:
  version: 2
  build-test-publish:
    jobs:
      - build:
          filters:  # required since `publish` has tag filters AND requires `build`
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:  # required since `publish` has tag filters AND requires `test`
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          